# Generated by Django 3.0.5 on 2020-04-30 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.TextField(default='blah', max_length=50)),
                ('description', models.TextField(max_length=120)),
                ('no_of_ratings', models.IntegerField(default=0)),
                ('avg_of_rating', models.FloatField(default=0)),
                ('img', models.ImageField(upload_to='food_pics')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=100)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_ids', models.TextField(max_length=300)),
                ('food_quantities', models.TextField(max_length=300)),
                ('notes', models.TextField(default='NONE', max_length=200)),
                ('deliver_location', models.TextField(max_length=200)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('location', models.TextField(max_length=150)),
                ('from_hour', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('to_hour', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('img', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('order_cnt', models.IntegerField(default=0)),
                ('no_of_ratings', models.IntegerField(default=0)),
                ('avg_of_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=100)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
