# Generated by Django 3.0.5 on 2020-05-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200430_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
