# Generated by Django 3.0.5 on 2020-05-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200510_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='avg_of_rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='no_of_ratings',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avg_of_rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='no_of_ratings',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_cnt',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
