# Generated by Django 3.0.5 on 2020-05-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20200514_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
