# Generated by Django 3.0.5 on 2020-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='total_price',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
