# Generated by Django 3.0.5 on 2020-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20200515_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='avg_rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='statistics',
            name='cnt_rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
