# Generated by Django 3.0.5 on 2020-05-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20200517_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
    ]
