# Generated by Django 3.0.5 on 2020-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20200520_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='month',
            field=models.IntegerField(default=5, editable=False),
        ),
        migrations.AddField(
            model_name='statistics',
            name='year',
            field=models.IntegerField(default=2020, editable=False),
        ),
    ]
