# Generated by Django 3.0.5 on 2020-05-28 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20200528_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='month',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='year',
        ),
        migrations.AddField(
            model_name='statistics',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 21, 6, 5, 919150), editable=False),
        ),
    ]
