# Generated by Django 3.0.5 on 2020-05-29 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20200528_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 13, 59, 57, 354892), editable=False),
        ),
    ]
