# Generated by Django 3.0.5 on 2020-05-29 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20200529_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 14, 4, 53, 28804), editable=False),
        ),
    ]
