# Generated by Django 3.0.5 on 2020-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20200529_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
