# Generated by Django 3.0.5 on 2020-07-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_auto_20200608_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='logo',
            new_name='img',
        ),
    ]
