# Generated by Django 3.0.5 on 2020-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_remove_food_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
