# Generated by Django 3.0.5 on 2020-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_food_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
