# Generated by Django 3.0.5 on 2020-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_psoted',
            new_name='date_posted',
        ),
    ]
