# Generated by Django 3.0.5 on 2020-05-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200513_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_cnt',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
