# Generated by Django 3.0.5 on 2020-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200509_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
